{
 "title": "Mining-Stats",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "BTC Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jsonstats_price_BTC",
     "measurement": "pool-stats",
     "query": "SELECT \"value\" *1440 FROM \"pool-stats\" WHERE (\"curr\" = 'etc' AND \"type\" = 'income') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "*1440" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "curr", "operator": "=", "value": "etc" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "income" }
     ]
    }
   ]
  },
  {
   "title": "ETC Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jsonstats_price_ETC",
     "measurement": "pool-stats",
     "query": "SELECT \"value\" *1440 FROM \"pool-stats\" WHERE (\"curr\" = 'etc' AND \"type\" = 'income') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "*1440" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "curr", "operator": "=", "value": "etc" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "income" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hiveos_rigs_power{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daily Power Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jsonstats_power_cost_USD", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hiveos_shares_accepted" }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hiveos_shares_rejected" }
   ]
  },
  {
   "title": "Hashrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(hiveos_gpu_hash)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Profitability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jsonstats_mining_profitability", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unpaid",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jsonstats_unpaid_balance_USD",
     "measurement": "pending-payout",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "curr", "operator": "=", "value": "eth" }
     ]
    }
   ]
  },
  {
   "title": "Ledger Wallet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jsonstats_wallet_balance_USD",
     "measurement": "pending-payout",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "curr", "operator": "=", "value": "eth" }
     ]
    }
   ]
  },
  {
   "title": "Mining Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hiveos_mining_duration" }
   ]
  },
  {
   "title": "GPU Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "KHs" } },
   "targets": [
    { "expr": "sum(hiveos_gpu_hash)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "hiveos_rigs_power" }
   ]
  },
  {
   "title": "3070 TI Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiveos_gpu_core_temp{model=\"GeForce RTX 3070 Ti LHR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2080 SUPER Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiveos_gpu_core_temp{model=\"GeForce RTX 2080 SUPER\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2080 Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiveos_gpu_core_temp{model=\"GeForce RTX 2080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "KHs" } },
   "targets": [
    { "expr": "hiveos_gpu_hash", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU Hashrate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "KHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hiveos_gpu_hash", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "3060 Ti Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiveos_gpu_core_temp{model=\"GeForce RTX 3060 Ti LHR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hiveos_gpu_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "3060 Ti Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hiveos_gpu_core_temp{model=\"GeForce RTX 3060 Ti\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payout Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "currencymBTC" } },
   "targets": [
    { "expr": "miner_current_balance" }
   ]
  }
 ]
}